name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

     # - name: Run ESLint
      #  run: npm run lint

      - name: Run tests with coverage and JUnit output
        run: |
          npm install --save-dev jest-junit
          npx jest --coverage --ci --reporters=default --reporters=jest-junit

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Upload JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: junit.xml

      - name: convert JUnit to Sonar format
        run: |
          node convert-junit-to-sonar.js

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.sources=.
            -Dsonar.tests=.
            -Dsonar.projectKey=abhisheklearnsjava_NodeJSWeb
            -Dsonar.organization=abhisheklearnsjava
            -Dsonar.inclusions=server.js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.verbose=true
            -Dsonar.testExecutionReportPaths=./sonar-test.xml
        env:
          SONAR_TOKEN: 'f3f4d596399ca42cb726accc8383568d8ed2354d'

    # The workflow will fail if linting or tests fail (non-zero
